#!/bin/csh -f

if ( $#argv < 1 ) then
  echo "Converts GATK interval_list to Plink/Seq region format"
  echo "Usage: interval_list_to_pseq_reg [INTERVAL_LIST_FILE]"
  exit 1
endif


set INPUT = $1

cat $INPUT | \
awk 'BEGIN{OFS="\t"; print "#CHR\tBP1\tBP2\tID"} \
{split($1,a,":"); chr=a[1]; \
if (match(chr,"chr")==0) {chr="chr"chr} \
split(a[2],b,"-"); bp1=b[1]; bp2=bp1; if (length(b) > 1) {bp2=b[2]} \
print chr,bp1,bp2,NR}'
